In [2]:
print('hello world')

hello world


In [ ]:
%pip install numpy pandas

## 차원 미니퀘스트 1번

In [4]:
import numpy as np

array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array.ndim)

3


## 차원 미니퀘스트 2번

In [5]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60])

array_2d = array.reshape(2, 3)

print(array_2d)

[[10 20 30]
 [40 50 60]]


## 차원 미니퀘스트 3번

In [6]:
import numpy as np

array = np.array([7, 14, 21])

array_2d = array[np.newaxis, :]

print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)

[[ 7 14 21]]
2
(1, 3)


## shape 미니퀘스트 1번

In [7]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


## shape 미니퀘스트 2번

In [9]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60])

new_array = array.reshape(2, 3)

print(new_array.shape)
print(new_array)

(2, 3)
[[10 20 30]
 [40 50 60]]


## shpae 미니퀘스트 3번

In [10]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_array = array.reshape(3, 2, 2)

print(new_array)
print(new_array.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


## 데이터 타입 미니퀘스트 1번

In [13]:
import numpy as np

array = np.array([10, 20, 30])

print(array.dtype)

int64


## 데이터 타입 미니퀘스트 2번

In [14]:
import numpy as np

array = np.array([1, 2, 3])

float_array = array.astype(float)

print(float_array)
print(float_array.dtype)

[1. 2. 3.]
float64


## 데이터 타입 미니퀘스트 3번

In [15]:
import numpy as np

array = np.array([100, 200, 300])

uint8_array = array.astype(np.uint8)

print(uint8_array)
print(uint8_array.nbytes)

[100 200  44]
3


## 인덱싱 미니퀘스트 1번

In [16]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

print(array[0])
print(array[-1])

10
50


## 인덱싱 미니퀘스트 2번

In [17]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

first_column = matrix[:, 0]
second_row = matrix[1, :]

print(first_column)
print(second_row)

[1 4 7]
[4 5 6]


## 인덱싱 미니퀘스트 3번

In [18]:
import numpy as np

array = np.array([5, 15, 8, 20, 3, 12])

selected = array[array > 10]
indexes = np.where(array > 10)

print(selected)
print(indexes)

[15 20 12]
(array([1, 3, 5]),)


## 연산 미니퀘스트 1번

In [19]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)

[5 7 9]


## 연산 미니퀘스트 2번

In [20]:
import numpy as np

matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

result = matrix + vector

print(result)

[[11 22 33]
 [41 52 63]]


## 연산 미니퀘스트 3번

In [21]:
import numpy as np

array = np.array([[3, 7, 2], [8, 4, 6]])

max_values = np.max(array, axis=0)

print(max_values)
print(max_values.ndim)

[8 7 6]
1


## 유니버셜 함수 미니퀘스트 1번

In [22]:
import numpy as np

array = np.array([1, 2, 3, 4])

result = np.square(array)

print(result)

[ 1  4  9 16]


## 유니버셜 함수 미니퀘스트 2번

In [23]:
import numpy as np

array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

np.add(array1, array2, out=array1)

print(array1)

[11 22 33]


## 유니버셜 함수 미니퀘스트 3번

In [24]:
import numpy as np

array = np.array([1, np.e, 10, 100])

log_array = np.log(array)

result = log_array[log_array > 1]

print(log_array)
print(result)

[0.         1.         2.30258509 4.60517019]
[2.30258509 4.60517019]
